Remove restutils, fixes #78
telekom/testerra pull request #120
Opened 2021-09-17 11:13 UTC by martingrossmann

RESTUtils are completly removed from Testerra. This component is still available here: https://github.com/telekom/testerra-legacy

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-09-17 11:17 UTC, mbeuthan approved these changes

2021-09-17 12:59 UTC, mreiche reviewed
kT

2021-09-17 13:06 UTC, mreiche requested changes
What about documentation?

2021-09-17 13:08 UTC, martingrossmann commented
> What about documentation?

RESTUtils were only used internal and were not part of the official documentation.

2021-09-18 17:55 UTC, mreiche approved these changes

2021-09-21 08:01 UTC, merged