Report: added ordering options to columns in tests view
telekom/testerra pull request #302
Opened 2023-01-05 15:56 UTC by sbke-mms

# Description

The table in the Tests view of the report can now be ordered by run id, method name, and class name. When ordering by class name the methods from the same class will be ordered by the method name. Default order is by class name.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-01-06 10:29 UTC, mbeuthan approved these changes

2023-01-06 15:44 UTC, mreiche requested changes

2023-01-06 15:44 UTC, mreiche commented on report-ng/app/src/components/classes/classes.ts
> +                case "method" :
Please consider using https://www.typescriptlang.org/docs/handbook/enums.html#string-enums

2023-01-16 15:49 UTC, sbke-mms commented on report-ng/app/src/components/classes/classes.ts
> +                case "method" :
Done

2023-01-17 10:52 UTC, mreiche approved these changes

2023-01-17 12:53 UTC, martingrossmann approved these changes

2023-01-17 12:53 UTC, merged