Feature/clearer visibility check methods
telekom/testerra pull request #309
Opened 2023-02-02 15:30 UTC by sbke-mms

# Description

Made new methods to check the visibility of elements. They should be easier to understand than the current `visibile()` method.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-02 16:21 UTC, martingrossmann requested changes

2023-02-02 16:21 UTC, martingrossmann commented on driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/asserts/DefaultUiElementAssertion.java
> +    public BinaryAssertion<Boolean> partiallyVisible() {
For a easier finding of thease methods via code completion I prefer the following names:
`visibleFull`
`visiblePartial`

2023-02-02 16:21 UTC, martingrossmann commented on driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/pageobjects/internal/asserts/LegacyGuiElementAssertWrapper.java
> +        if(complete) {
Please execute autoformat of IntelliJ

2023-03-02 16:22 UTC, martingrossmann approved these changes

2023-03-03 06:49 UTC, mbeuthan approved these changes

2023-03-08 06:45 UTC, merged