Feature/timing collector
telekom/testerra pull request #351
Opened 2023-08-29 09:21 UTC by martingrossmann

# Description

This PR adds a `MetricsCollector` to store different time metrics. Its independent of contexts to not overload the context data model.

Implemented:
- load of a base URL
- load of a session

Planned:
- load of pages
- add charts to ReportNG

Not decided:
- migration of lifetime information of session context, method context, ... to `MetricsCollector`

Fixes #118 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-11 12:00 UTC, mreiche requested changes

2023-10-11 12:00 UTC, mreiche commented on report-model/src/main/proto/framework.proto
> +    MethodContext method_context = 2;
Same goes here

2023-10-16 11:07 UTC, martingrossmann commented on report-model/src/main/proto/framework.proto
> +    SessionContext session_context = 2;
I switched to ids to be consistent to other model definitions.

2023-10-17 07:50 UTC, mreiche commented on core/src/main/java/eu/tsystems/mms/tic/testframework/internal/metrics/MetricsController.java
> +    public Duration readDuration(SessionContext context, MetricsType type) {
`Duration` is immutable, that means this could should be called `getDuration` IMHO.

2023-10-19 09:27 UTC, martingrossmann commented on core/src/main/java/eu/tsystems/mms/tic/testframework/internal/MetricsController.java
> +            instance = new MetricsController();
Changed to have Dependency injection and updated `MetricsController` to be _generic_

2023-10-19 09:42 UTC, mreiche approved these changes

2023-10-23 09:53 UTC, merged