[WIP] Replace EventFiringWebDriver
telekom/testerra pull request #381
Opened 2024-01-05 14:22 UTC by martingrossmann

# Description

The listener `EventFiringWebDriver` is deprecated and was also removed in current Selenium trunk (https://github.com/SeleniumHQ/selenium/pull/13200). 

Selenium now provides `EventFiringDecorator` and `WebDriverListener`.

There is still an open PR which adds some more methods to `WebDriverListener` we want to use:
- [ ] https://github.com/SeleniumHQ/selenium/pull/13210
- [ ] Selenium 4.17 released

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-02-20 16:48 UTC, mreiche requested changes

2024-02-20 16:48 UTC, mreiche commented on driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/VisualEventDriverListener.java
> +    private boolean isDemo = Testerra.Properties.DEMO_MODE.asBool();
This is a bad practice, because it prevents overriding Properties during runtime.

2024-02-20 16:48 UTC, mreiche commented on driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/VisualEventDriverListener.java
> +        if (element != null && isDemo) {
```java
if (element != null && Testerra.Properties.DEMO_MODE.asBool()) {}
```

2024-02-20 16:48 UTC, mreiche commented on driver-ui-desktop/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverFactory.java
> +        VisualEventDriverListener visualListener = new VisualEventDriverListener();
Why not instantiating `VisualEventDriverListener` only when `Testerra.Properties.DEMO_MODE.asBool()`?

2024-02-26 13:15 UTC, martingrossmann commented on driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/VisualEventDriverListener.java
> +        if (element != null && isDemo) {
Updated

2024-02-26 17:47 UTC, mreiche approved these changes

2024-02-27 08:28 UTC, merged