Fix/imap connector delete message
telekom/testerra pull request #388
Opened 2024-01-12 09:18 UTC by clemensgrosse

# Description

- fix of delete message in AbstractInboxConnector
- deletion of deprecated methods in AbstractInboxConnector
- adding usage of latest testerra code for MailConnectorTest (current methods of AbstractInboxConnector, PropertyManagerProvider, ASSERT)
- correcting T11 in MailConnectorTest

## Type of change

Please delete options that are not relevant.

- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] New and existing tests pass locally with my changes

2024-01-12 09:39 UTC, martingrossmann commented on mail-connector/src/main/java/eu/tsystems/mms/tic/testframework/mailconnector/util/AbstractInboxConnector.java
> +            log().info(logMessageSearchTerm);
Please use default logging syntax with `{}`, e.g. `log().info("Checking messages from {}", getInboxFolder())`

2024-01-12 09:43 UTC, martingrossmann commented
Please recheck the mail connector docs if there is needed an update.

2024-01-12 09:48 UTC, martingrossmann requested changes

2024-01-12 09:48 UTC, martingrossmann commented on mail-connector/src/test/java/eu/tsystems/mms/tic/testframework/mailconnector/test/MailConnectorTest.java
> +            if (emailList.isEmpty()) {
Please use an `Assert` to check for `emailList.isEmpty`. I think the `try...catch` is not needed here.

2024-01-15 09:54 UTC, martingrossmann commented on mail-connector/src/main/java/eu/tsystems/mms/tic/testframework/mailconnector/util/EmailQuery.java
> +    private long pauseMs = PROPERTY_MANAGER.getLongProperty(POLLING_TIMER_SECONDS_PROPERTY, "10") * 1000;
Default value should not `"10"`, but `10_000L` and the calculation with `* 1000` ist not needed any more.

2024-01-15 11:55 UTC, mbeuthan approved these changes

2024-01-19 11:41 UTC, martingrossmann approved these changes

2024-01-19 11:41 UTC, merged