Feature/generate report on interruption
telekom/testerra pull request #397
Opened 2024-02-26 11:30 UTC by clemensgrosse

# Description

Added mechanism to generate a report in case of unexpected abortion of test execution.
A ShutDownHook triggers on JVM finish in successful and failure cases. Report generation is then triggered within the Hook, if no report has been generated before. with sending a ExecutionAbortEvent.
Flag for generated report is set once only in ExecutionEndListener, in case of successful end of test execution (ExecutionFinishEvent received by the mentioned Listener).

## Type of change

- [x ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules

2024-02-26 12:06 UTC, mreiche submitted a review, later dismissed

2024-02-26 13:57 UTC, martingrossmann requested changes

2024-02-26 13:57 UTC, martingrossmann commented on core/src/main/java/eu/tsystems/mms/tic/testframework/common/JVMExitHook.java
> +package eu.tsystems.mms.tic.testframework.common;
Please add the license text as a file header

2024-02-29 08:07 UTC, martingrossmann commented
As discussed please add a short note in documentation about this helpful feature.

2024-02-29 10:04 UTC, mreiche approved these changes

2024-02-29 17:44 UTC, mreiche commented on docs/src/docs/reports/aborted-execution.adoc
> +In case of unexpected abortion of a test execution the report is generated, too. . Due to abortion of still running test methods
Please fix spelling "generated, too. . Due"

2024-03-01 06:52 UTC, martingrossmann commented on docs/src/docs/jvm/jvm-exit-hook.adoc
> +To avoid overriding the already existing report, the `JVMExitHook` only triggers when this flag is false, as this is the only indicator of an unexpected exit and a missing report. It then sends the <
Your link to `ExecutionAbortEvent` does not work anymore because it's an own chapter now. ;-)

2024-03-01 07:38 UTC, mreiche submitted a review, later dismissed

2024-03-04 08:04 UTC, merged