Add video tab
telekom/testerra pull request #407
Opened 2024-03-25 07:55 UTC by selinanatschke-mms

# Description

* split up sessions tab, that included session information and video into two separate tabs: browser info and video
* added more information to the browser info tab e.g. session metrics
* added linking between video id and session id if they are available 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-25 11:25 UTC, mreiche approved these changes

2024-03-27 06:55 UTC, martingrossmann requested changes

2024-03-27 06:55 UTC, martingrossmann commented on report-ng/app/src/components/method-details/method.ts
> +                        if(methodDetails.sessionContexts.map(context => context.videoId).length > 0){
Please doubecheck this line. The Video tab is shown even no video is available.

2024-03-27 14:47 UTC, mreiche commented on report-ng/app/src/components/method-details/method.ts
>                              routeConfig.settings.count = methodDetails.sessionContexts.map(context => context.videoId).length;
routeConfig.settings.count = contextsWithVideos.length

2024-03-27 14:49 UTC, mreiche commented on report-ng/app/src/components/method-details/browser-info.html
> +  ~ (C) 2020, Mike Reiche, T-Systems Multimedia Solutions GmbH, Deutsche Telekom AG
Thanks ;)

2024-03-27 14:52 UTC, mreiche requested changes

2024-03-27 14:52 UTC, mreiche commented on report-ng/app/src/components/method-details/method.ts
> +                            routeConfig.settings.count = methodDetails.sessionContexts.map(context => context.videoId).length;
routeConfig.settings.count = contextsWithVideos.length

2024-04-02 09:20 UTC, mreiche approved these changes

2024-04-08 10:01 UTC, martingrossmann commented
Looks great for me. But please fix the report test `testT01_checkDisplayedSessionGotContent`. It still tries to find the old Sessions tab.

2024-04-23 07:06 UTC, martingrossmann requested changes

2024-04-23 07:06 UTC, martingrossmann commented on docs/src/images/report-ng-22.png
Why you changed the image of the classes view to method details view? This screenshot is used in report chapter `More on Assertions`

2024-04-23 07:06 UTC, martingrossmann commented on docs/src/images/report-ng-collected-assertions-01.png
This screenshot is used in report chapter `More on Assertions - Collected assertions`. Now we have 2 images of steps view.

2024-04-30 10:22 UTC, mreiche submitted a review, later dismissed

2024-04-30 10:22 UTC, mreiche commented on report-ng-tests/src/main/java/io/testerra/report/test/pages/report/methodReport/ReportVideoTab.java
> +        this.id.assertThat().text().contains(id);
Use `isContaining()` or `contains(id).is(true)`

2024-04-30 10:22 UTC, mreiche commented on report-ng-tests/src/main/java/io/testerra/report/test/pages/report/methodReport/ReportVideoTab.java
> +        this.browser.assertThat().text().contains(browser);
Use `isContaining()` or `contains(id).is(true)`

2024-05-06 07:24 UTC, martingrossmann commented on report-ng-tests/src/main/java/io/testerra/report/test/pages/report/methodReport/ReportVideoTab.java
> +        this.id.assertThat().displayed();
Like discussed this check is duplicated. If you want to check the ID, you should take it from Browser info.

2024-05-07 09:35 UTC, martingrossmann approved these changes

2024-05-07 09:35 UTC, merged